load_IDT:
    lidt idt
    ret

idt_handler_0:
    mov BYTE [0xE0000000], 0
    hlt

idt_handler_1:
    mov BYTE [0xE0000000], 1
    hlt

idt_handler_2:
    mov BYTE [0xE0000000], 2
    hlt

idt_handler_3:
    mov BYTE [0xE0000000], 3
    hlt

idt_handler_4:
    mov BYTE [0xE0000000], 4
    hlt

idt_handler_5:
    mov BYTE [0xE0000000], 5
    hlt

idt_handler_6:
    mov BYTE [0xE0000000], 6
    hlt

idt_handler_7:
    mov BYTE [0xE0000000], 7
    hlt

idt_handler_8:
    mov BYTE [0xE0000000], 8
    hlt

idt_handler_9:
    mov BYTE [0xE0000000], 9
    hlt

idt_handler_10:
    mov BYTE [0xE0000000], 10
    hlt

idt_handler_11:
    mov BYTE [0xE0000000], 11
    hlt

idt_handler_12:
    mov BYTE [0xE0000000], 12
    hlt

idt_handler_13:
    mov BYTE [0xE0000000], 13
    hlt

idt_handler_14:
    mov BYTE [0xE0000000], 14
    hlt

idt_handler_15:
    mov BYTE [0xE0000000], 15
    hlt

idt_handler_16:
    mov BYTE [0xE0000000], 16
    hlt

idt_handler_17:
    mov BYTE [0xE0000000], 17
    hlt

idt_handler_18:
    mov BYTE [0xE0000000], 18
    hlt

idt_handler_19:
    mov BYTE [0xE0000000], 19
    hlt

idt_handler_20:
    mov BYTE [0xE0000000], 20
    hlt

idt_handler_21:
    mov BYTE [0xE0000000], 21
    hlt

idt_handler_22:
    mov BYTE [0xE0000000], 22
    hlt

idt_handler_23:
    mov BYTE [0xE0000000], 23
    hlt

idt_handler_24:
    mov BYTE [0xE0000000], 24
    hlt

idt_handler_25:
    mov BYTE [0xE0000000], 25
    hlt

idt_handler_26:
    mov BYTE [0xE0000000], 26
    hlt

idt_handler_27:
    mov BYTE [0xE0000000], 27
    hlt

idt_handler_28:
    mov BYTE [0xE0000000], 28
    hlt

idt_handler_29:
    mov BYTE [0xE0000000], 29
    hlt

idt_handler_30:
    mov BYTE [0xE0000000], 30
    hlt

idt_handler_31:
    mov BYTE [0xE0000000], 31
    hlt

idt_handler_32:
    mov BYTE [0xE0000000], 32
    hlt

idt_handler_33:
    mov BYTE [0xE0000000], 33
    hlt

idt_handler_34:
    mov BYTE [0xE0000000], 34
    hlt

idt_handler_35:
    mov BYTE [0xE0000000], 35
    hlt

idt_handler_36:
    mov BYTE [0xE0000000], 36
    hlt

idt_handler_37:
    mov BYTE [0xE0000000], 37
    hlt

idt_handler_38:
    mov BYTE [0xE0000000], 38
    hlt

idt_handler_39:
    mov BYTE [0xE0000000], 39
    hlt

idt_handler_40:
    mov BYTE [0xE0000000], 40
    hlt

idt_handler_41:
    mov BYTE [0xE0000000], 41
    hlt

idt_handler_42:
    mov BYTE [0xE0000000], 42
    hlt

idt_handler_43:
    mov BYTE [0xE0000000], 43
    hlt

idt_handler_44:
    mov BYTE [0xE0000000], 44
    hlt

idt_handler_45:
    mov BYTE [0xE0000000], 45
    hlt

idt_handler_46:
    mov BYTE [0xE0000000], 46
    hlt

idt_handler_47:
    mov BYTE [0xE0000000], 47
    hlt

idt_handler_48:
    mov BYTE [0xE0000000], 48
    hlt

idt_handler_49:
    mov BYTE [0xE0000000], 49
    hlt

idt_handler_50:
    mov BYTE [0xE0000000], 50
    hlt

idt_handler_51:
    mov BYTE [0xE0000000], 51
    hlt

idt_handler_52:
    mov BYTE [0xE0000000], 52
    hlt

idt_handler_53:
    mov BYTE [0xE0000000], 53
    hlt

idt_handler_54:
    mov BYTE [0xE0000000], 54
    hlt

idt_handler_55:
    mov BYTE [0xE0000000], 55
    hlt

idt_handler_56:
    mov BYTE [0xE0000000], 56
    hlt

idt_handler_57:
    mov BYTE [0xE0000000], 57
    hlt

idt_handler_58:
    mov BYTE [0xE0000000], 58
    hlt

idt_handler_59:
    mov BYTE [0xE0000000], 59
    hlt

idt_handler_60:
    mov BYTE [0xE0000000], 60
    hlt

idt_handler_61:
    mov BYTE [0xE0000000], 61
    hlt

idt_handler_62:
    mov BYTE [0xE0000000], 62
    hlt

idt_handler_63:
    mov BYTE [0xE0000000], 63
    hlt

idt_handler_64:
    mov BYTE [0xE0000000], 64
    hlt

idt_handler_65:
    mov BYTE [0xE0000000], 65
    hlt

idt_handler_66:
    mov BYTE [0xE0000000], 66
    hlt

idt_handler_67:
    mov BYTE [0xE0000000], 67
    hlt

idt_handler_68:
    mov BYTE [0xE0000000], 68
    hlt

idt_handler_69:
    mov BYTE [0xE0000000], 69
    hlt

idt_handler_70:
    mov BYTE [0xE0000000], 70
    hlt

idt_handler_71:
    mov BYTE [0xE0000000], 71
    hlt

idt_handler_72:
    mov BYTE [0xE0000000], 72
    hlt

idt_handler_73:
    mov BYTE [0xE0000000], 73
    hlt

idt_handler_74:
    mov BYTE [0xE0000000], 74
    hlt

idt_handler_75:
    mov BYTE [0xE0000000], 75
    hlt

idt_handler_76:
    mov BYTE [0xE0000000], 76
    hlt

idt_handler_77:
    mov BYTE [0xE0000000], 77
    hlt

idt_handler_78:
    mov BYTE [0xE0000000], 78
    hlt

idt_handler_79:
    mov BYTE [0xE0000000], 79
    hlt

idt_handler_80:
    mov BYTE [0xE0000000], 80
    hlt

idt_handler_81:
    mov BYTE [0xE0000000], 81
    hlt

idt_handler_82:
    mov BYTE [0xE0000000], 82
    hlt

idt_handler_83:
    mov BYTE [0xE0000000], 83
    hlt

idt_handler_84:
    mov BYTE [0xE0000000], 84
    hlt

idt_handler_85:
    mov BYTE [0xE0000000], 85
    hlt

idt_handler_86:
    mov BYTE [0xE0000000], 86
    hlt

idt_handler_87:
    mov BYTE [0xE0000000], 87
    hlt

idt_handler_88:
    mov BYTE [0xE0000000], 88
    hlt

idt_handler_89:
    mov BYTE [0xE0000000], 89
    hlt

idt_handler_90:
    mov BYTE [0xE0000000], 90
    hlt

idt_handler_91:
    mov BYTE [0xE0000000], 91
    hlt

idt_handler_92:
    mov BYTE [0xE0000000], 92
    hlt

idt_handler_93:
    mov BYTE [0xE0000000], 93
    hlt

idt_handler_94:
    mov BYTE [0xE0000000], 94
    hlt

idt_handler_95:
    mov BYTE [0xE0000000], 95
    hlt

idt_handler_96:
    mov BYTE [0xE0000000], 96
    hlt

idt_handler_97:
    mov BYTE [0xE0000000], 97
    hlt

idt_handler_98:
    mov BYTE [0xE0000000], 98
    hlt

idt_handler_99:
    mov BYTE [0xE0000000], 99
    hlt

idt_handler_100:
    mov BYTE [0xE0000000], 100
    hlt

idt_handler_101:
    mov BYTE [0xE0000000], 101
    hlt

idt_handler_102:
    mov BYTE [0xE0000000], 102
    hlt

idt_handler_103:
    mov BYTE [0xE0000000], 103
    hlt

idt_handler_104:
    mov BYTE [0xE0000000], 104
    hlt

idt_handler_105:
    mov BYTE [0xE0000000], 105
    hlt

idt_handler_106:
    mov BYTE [0xE0000000], 106
    hlt

idt_handler_107:
    mov BYTE [0xE0000000], 107
    hlt

idt_handler_108:
    mov BYTE [0xE0000000], 108
    hlt

idt_handler_109:
    mov BYTE [0xE0000000], 109
    hlt

idt_handler_110:
    mov BYTE [0xE0000000], 110
    hlt

idt_handler_111:
    mov BYTE [0xE0000000], 111
    hlt

idt_handler_112:
    mov BYTE [0xE0000000], 112
    hlt

idt_handler_113:
    mov BYTE [0xE0000000], 113
    hlt

idt_handler_114:
    mov BYTE [0xE0000000], 114
    hlt

idt_handler_115:
    mov BYTE [0xE0000000], 115
    hlt

idt_handler_116:
    mov BYTE [0xE0000000], 116
    hlt

idt_handler_117:
    mov BYTE [0xE0000000], 117
    hlt

idt_handler_118:
    mov BYTE [0xE0000000], 118
    hlt

idt_handler_119:
    mov BYTE [0xE0000000], 119
    hlt

idt_handler_120:
    mov BYTE [0xE0000000], 120
    hlt

idt_handler_121:
    mov BYTE [0xE0000000], 121
    hlt

idt_handler_122:
    mov BYTE [0xE0000000], 122
    hlt

idt_handler_123:
    mov BYTE [0xE0000000], 123
    hlt

idt_handler_124:
    mov BYTE [0xE0000000], 124
    hlt

idt_handler_125:
    mov BYTE [0xE0000000], 125
    hlt

idt_handler_126:
    mov BYTE [0xE0000000], 126
    hlt

idt_handler_127:
    mov BYTE [0xE0000000], 127
    hlt

idt_handler_128:
    mov BYTE [0xE0000000], 128
    hlt

idt_handler_129:
    mov BYTE [0xE0000000], 129
    hlt

idt_handler_130:
    mov BYTE [0xE0000000], 130
    hlt

idt_handler_131:
    mov BYTE [0xE0000000], 131
    hlt

idt_handler_132:
    mov BYTE [0xE0000000], 132
    hlt

idt_handler_133:
    mov BYTE [0xE0000000], 133
    hlt

idt_handler_134:
    mov BYTE [0xE0000000], 134
    hlt

idt_handler_135:
    mov BYTE [0xE0000000], 135
    hlt

idt_handler_136:
    mov BYTE [0xE0000000], 136
    hlt

idt_handler_137:
    mov BYTE [0xE0000000], 137
    hlt

idt_handler_138:
    mov BYTE [0xE0000000], 138
    hlt

idt_handler_139:
    mov BYTE [0xE0000000], 139
    hlt

idt_handler_140:
    mov BYTE [0xE0000000], 140
    hlt

idt_handler_141:
    mov BYTE [0xE0000000], 141
    hlt

idt_handler_142:
    mov BYTE [0xE0000000], 142
    hlt

idt_handler_143:
    mov BYTE [0xE0000000], 143
    hlt

idt_handler_144:
    mov BYTE [0xE0000000], 144
    hlt

idt_handler_145:
    mov BYTE [0xE0000000], 145
    hlt

idt_handler_146:
    mov BYTE [0xE0000000], 146
    hlt

idt_handler_147:
    mov BYTE [0xE0000000], 147
    hlt

idt_handler_148:
    mov BYTE [0xE0000000], 148
    hlt

idt_handler_149:
    mov BYTE [0xE0000000], 149
    hlt

idt_handler_150:
    mov BYTE [0xE0000000], 150
    hlt

idt_handler_151:
    mov BYTE [0xE0000000], 151
    hlt

idt_handler_152:
    mov BYTE [0xE0000000], 152
    hlt

idt_handler_153:
    mov BYTE [0xE0000000], 153
    hlt

idt_handler_154:
    mov BYTE [0xE0000000], 154
    hlt

idt_handler_155:
    mov BYTE [0xE0000000], 155
    hlt

idt_handler_156:
    mov BYTE [0xE0000000], 156
    hlt

idt_handler_157:
    mov BYTE [0xE0000000], 157
    hlt

idt_handler_158:
    mov BYTE [0xE0000000], 158
    hlt

idt_handler_159:
    mov BYTE [0xE0000000], 159
    hlt

idt_handler_160:
    mov BYTE [0xE0000000], 160
    hlt

idt_handler_161:
    mov BYTE [0xE0000000], 161
    hlt

idt_handler_162:
    mov BYTE [0xE0000000], 162
    hlt

idt_handler_163:
    mov BYTE [0xE0000000], 163
    hlt

idt_handler_164:
    mov BYTE [0xE0000000], 164
    hlt

idt_handler_165:
    mov BYTE [0xE0000000], 165
    hlt

idt_handler_166:
    mov BYTE [0xE0000000], 166
    hlt

idt_handler_167:
    mov BYTE [0xE0000000], 167
    hlt

idt_handler_168:
    mov BYTE [0xE0000000], 168
    hlt

idt_handler_169:
    mov BYTE [0xE0000000], 169
    hlt

idt_handler_170:
    mov BYTE [0xE0000000], 170
    hlt

idt_handler_171:
    mov BYTE [0xE0000000], 171
    hlt

idt_handler_172:
    mov BYTE [0xE0000000], 172
    hlt

idt_handler_173:
    mov BYTE [0xE0000000], 173
    hlt

idt_handler_174:
    mov BYTE [0xE0000000], 174
    hlt

idt_handler_175:
    mov BYTE [0xE0000000], 175
    hlt

idt_handler_176:
    mov BYTE [0xE0000000], 176
    hlt

idt_handler_177:
    mov BYTE [0xE0000000], 177
    hlt

idt_handler_178:
    mov BYTE [0xE0000000], 178
    hlt

idt_handler_179:
    mov BYTE [0xE0000000], 179
    hlt

idt_handler_180:
    mov BYTE [0xE0000000], 180
    hlt

idt_handler_181:
    mov BYTE [0xE0000000], 181
    hlt

idt_handler_182:
    mov BYTE [0xE0000000], 182
    hlt

idt_handler_183:
    mov BYTE [0xE0000000], 183
    hlt

idt_handler_184:
    mov BYTE [0xE0000000], 184
    hlt

idt_handler_185:
    mov BYTE [0xE0000000], 185
    hlt

idt_handler_186:
    mov BYTE [0xE0000000], 186
    hlt

idt_handler_187:
    mov BYTE [0xE0000000], 187
    hlt

idt_handler_188:
    mov BYTE [0xE0000000], 188
    hlt

idt_handler_189:
    mov BYTE [0xE0000000], 189
    hlt

idt_handler_190:
    mov BYTE [0xE0000000], 190
    hlt

idt_handler_191:
    mov BYTE [0xE0000000], 191
    hlt

idt_handler_192:
    mov BYTE [0xE0000000], 192
    hlt

idt_handler_193:
    mov BYTE [0xE0000000], 193
    hlt

idt_handler_194:
    mov BYTE [0xE0000000], 194
    hlt

idt_handler_195:
    mov BYTE [0xE0000000], 195
    hlt

idt_handler_196:
    mov BYTE [0xE0000000], 196
    hlt

idt_handler_197:
    mov BYTE [0xE0000000], 197
    hlt

idt_handler_198:
    mov BYTE [0xE0000000], 198
    hlt

idt_handler_199:
    mov BYTE [0xE0000000], 199
    hlt

idt_handler_200:
    mov BYTE [0xE0000000], 200
    hlt

idt_handler_201:
    mov BYTE [0xE0000000], 201
    hlt

idt_handler_202:
    mov BYTE [0xE0000000], 202
    hlt

idt_handler_203:
    mov BYTE [0xE0000000], 203
    hlt

idt_handler_204:
    mov BYTE [0xE0000000], 204
    hlt

idt_handler_205:
    mov BYTE [0xE0000000], 205
    hlt

idt_handler_206:
    mov BYTE [0xE0000000], 206
    hlt

idt_handler_207:
    mov BYTE [0xE0000000], 207
    hlt

idt_handler_208:
    mov BYTE [0xE0000000], 208
    hlt

idt_handler_209:
    mov BYTE [0xE0000000], 209
    hlt

idt_handler_210:
    mov BYTE [0xE0000000], 210
    hlt

idt_handler_211:
    mov BYTE [0xE0000000], 211
    hlt

idt_handler_212:
    mov BYTE [0xE0000000], 212
    hlt

idt_handler_213:
    mov BYTE [0xE0000000], 213
    hlt

idt_handler_214:
    mov BYTE [0xE0000000], 214
    hlt

idt_handler_215:
    mov BYTE [0xE0000000], 215
    hlt

idt_handler_216:
    mov BYTE [0xE0000000], 216
    hlt

idt_handler_217:
    mov BYTE [0xE0000000], 217
    hlt

idt_handler_218:
    mov BYTE [0xE0000000], 218
    hlt

idt_handler_219:
    mov BYTE [0xE0000000], 219
    hlt

idt_handler_220:
    mov BYTE [0xE0000000], 220
    hlt

idt_handler_221:
    mov BYTE [0xE0000000], 221
    hlt

idt_handler_222:
    mov BYTE [0xE0000000], 222
    hlt

idt_handler_223:
    mov BYTE [0xE0000000], 223
    hlt

idt_handler_224:
    mov BYTE [0xE0000000], 224
    hlt

idt_handler_225:
    mov BYTE [0xE0000000], 225
    hlt

idt_handler_226:
    mov BYTE [0xE0000000], 226
    hlt

idt_handler_227:
    mov BYTE [0xE0000000], 227
    hlt

idt_handler_228:
    mov BYTE [0xE0000000], 228
    hlt

idt_handler_229:
    mov BYTE [0xE0000000], 229
    hlt

idt_handler_230:
    mov BYTE [0xE0000000], 230
    hlt

idt_handler_231:
    mov BYTE [0xE0000000], 231
    hlt

idt_handler_232:
    mov BYTE [0xE0000000], 232
    hlt

idt_handler_233:
    mov BYTE [0xE0000000], 233
    hlt

idt_handler_234:
    mov BYTE [0xE0000000], 234
    hlt

idt_handler_235:
    mov BYTE [0xE0000000], 235
    hlt

idt_handler_236:
    mov BYTE [0xE0000000], 236
    hlt

idt_handler_237:
    mov BYTE [0xE0000000], 237
    hlt

idt_handler_238:
    mov BYTE [0xE0000000], 238
    hlt

idt_handler_239:
    mov BYTE [0xE0000000], 239
    hlt

idt_handler_240:
    mov BYTE [0xE0000000], 240
    hlt

idt_handler_241:
    mov BYTE [0xE0000000], 241
    hlt

idt_handler_242:
    mov BYTE [0xE0000000], 242
    hlt

idt_handler_243:
    mov BYTE [0xE0000000], 243
    hlt

idt_handler_244:
    mov BYTE [0xE0000000], 244
    hlt

idt_handler_245:
    mov BYTE [0xE0000000], 245
    hlt

idt_handler_246:
    mov BYTE [0xE0000000], 246
    hlt

idt_handler_247:
    mov BYTE [0xE0000000], 247
    hlt

idt_handler_248:
    mov BYTE [0xE0000000], 248
    hlt

idt_handler_249:
    mov BYTE [0xE0000000], 249
    hlt

idt_handler_250:
    mov BYTE [0xE0000000], 250
    hlt

idt_handler_251:
    mov BYTE [0xE0000000], 251
    hlt

idt_handler_252:
    mov BYTE [0xE0000000], 252
    hlt

idt_handler_253:
    mov BYTE [0xE0000000], 253
    hlt

idt_handler_254:
    mov BYTE [0xE0000000], 254
    hlt

idt_handler_255:
    mov BYTE [0xE0000000], 255
    hlt

idt:
.entry0:
    db 1
    dq idt_handler_0
.entry1:
    db 1
    dq idt_handler_1
.entry2:
    db 1
    dq idt_handler_2
.entry3:
    db 1
    dq idt_handler_3
.entry4:
    db 1
    dq idt_handler_4
.entry5:
    db 1
    dq idt_handler_5
.entry6:
    db 1
    dq idt_handler_6
.entry7:
    db 1
    dq idt_handler_7
.entry8:
    db 1
    dq idt_handler_8
.entry9:
    db 1
    dq idt_handler_9
.entry10:
    db 1
    dq idt_handler_10
.entry11:
    db 1
    dq idt_handler_11
.entry12:
    db 1
    dq idt_handler_12
.entry13:
    db 1
    dq idt_handler_13
.entry14:
    db 1
    dq idt_handler_14
.entry15:
    db 1
    dq idt_handler_15
.entry16:
    db 1
    dq idt_handler_16
.entry17:
    db 1
    dq idt_handler_17
.entry18:
    db 1
    dq idt_handler_18
.entry19:
    db 1
    dq idt_handler_19
.entry20:
    db 1
    dq idt_handler_20
.entry21:
    db 1
    dq idt_handler_21
.entry22:
    db 1
    dq idt_handler_22
.entry23:
    db 1
    dq idt_handler_23
.entry24:
    db 1
    dq idt_handler_24
.entry25:
    db 1
    dq idt_handler_25
.entry26:
    db 1
    dq idt_handler_26
.entry27:
    db 1
    dq idt_handler_27
.entry28:
    db 1
    dq idt_handler_28
.entry29:
    db 1
    dq idt_handler_29
.entry30:
    db 1
    dq idt_handler_30
.entry31:
    db 1
    dq idt_handler_31
.entry32:
    db 1
    dq idt_handler_32
.entry33:
    db 1
    dq idt_handler_33
.entry34:
    db 1
    dq idt_handler_34
.entry35:
    db 1
    dq idt_handler_35
.entry36:
    db 1
    dq idt_handler_36
.entry37:
    db 1
    dq idt_handler_37
.entry38:
    db 1
    dq idt_handler_38
.entry39:
    db 1
    dq idt_handler_39
.entry40:
    db 1
    dq idt_handler_40
.entry41:
    db 1
    dq idt_handler_41
.entry42:
    db 1
    dq idt_handler_42
.entry43:
    db 1
    dq idt_handler_43
.entry44:
    db 1
    dq idt_handler_44
.entry45:
    db 1
    dq idt_handler_45
.entry46:
    db 1
    dq idt_handler_46
.entry47:
    db 1
    dq idt_handler_47
.entry48:
    db 1
    dq idt_handler_48
.entry49:
    db 1
    dq idt_handler_49
.entry50:
    db 1
    dq idt_handler_50
.entry51:
    db 1
    dq idt_handler_51
.entry52:
    db 1
    dq idt_handler_52
.entry53:
    db 1
    dq idt_handler_53
.entry54:
    db 1
    dq idt_handler_54
.entry55:
    db 1
    dq idt_handler_55
.entry56:
    db 1
    dq idt_handler_56
.entry57:
    db 1
    dq idt_handler_57
.entry58:
    db 1
    dq idt_handler_58
.entry59:
    db 1
    dq idt_handler_59
.entry60:
    db 1
    dq idt_handler_60
.entry61:
    db 1
    dq idt_handler_61
.entry62:
    db 1
    dq idt_handler_62
.entry63:
    db 1
    dq idt_handler_63
.entry64:
    db 1
    dq idt_handler_64
.entry65:
    db 1
    dq idt_handler_65
.entry66:
    db 1
    dq idt_handler_66
.entry67:
    db 1
    dq idt_handler_67
.entry68:
    db 1
    dq idt_handler_68
.entry69:
    db 1
    dq idt_handler_69
.entry70:
    db 1
    dq idt_handler_70
.entry71:
    db 1
    dq idt_handler_71
.entry72:
    db 1
    dq idt_handler_72
.entry73:
    db 1
    dq idt_handler_73
.entry74:
    db 1
    dq idt_handler_74
.entry75:
    db 1
    dq idt_handler_75
.entry76:
    db 1
    dq idt_handler_76
.entry77:
    db 1
    dq idt_handler_77
.entry78:
    db 1
    dq idt_handler_78
.entry79:
    db 1
    dq idt_handler_79
.entry80:
    db 1
    dq idt_handler_80
.entry81:
    db 1
    dq idt_handler_81
.entry82:
    db 1
    dq idt_handler_82
.entry83:
    db 1
    dq idt_handler_83
.entry84:
    db 1
    dq idt_handler_84
.entry85:
    db 1
    dq idt_handler_85
.entry86:
    db 1
    dq idt_handler_86
.entry87:
    db 1
    dq idt_handler_87
.entry88:
    db 1
    dq idt_handler_88
.entry89:
    db 1
    dq idt_handler_89
.entry90:
    db 1
    dq idt_handler_90
.entry91:
    db 1
    dq idt_handler_91
.entry92:
    db 1
    dq idt_handler_92
.entry93:
    db 1
    dq idt_handler_93
.entry94:
    db 1
    dq idt_handler_94
.entry95:
    db 1
    dq idt_handler_95
.entry96:
    db 1
    dq idt_handler_96
.entry97:
    db 1
    dq idt_handler_97
.entry98:
    db 1
    dq idt_handler_98
.entry99:
    db 1
    dq idt_handler_99
.entry100:
    db 1
    dq idt_handler_100
.entry101:
    db 1
    dq idt_handler_101
.entry102:
    db 1
    dq idt_handler_102
.entry103:
    db 1
    dq idt_handler_103
.entry104:
    db 1
    dq idt_handler_104
.entry105:
    db 1
    dq idt_handler_105
.entry106:
    db 1
    dq idt_handler_106
.entry107:
    db 1
    dq idt_handler_107
.entry108:
    db 1
    dq idt_handler_108
.entry109:
    db 1
    dq idt_handler_109
.entry110:
    db 1
    dq idt_handler_110
.entry111:
    db 1
    dq idt_handler_111
.entry112:
    db 1
    dq idt_handler_112
.entry113:
    db 1
    dq idt_handler_113
.entry114:
    db 1
    dq idt_handler_114
.entry115:
    db 1
    dq idt_handler_115
.entry116:
    db 1
    dq idt_handler_116
.entry117:
    db 1
    dq idt_handler_117
.entry118:
    db 1
    dq idt_handler_118
.entry119:
    db 1
    dq idt_handler_119
.entry120:
    db 1
    dq idt_handler_120
.entry121:
    db 1
    dq idt_handler_121
.entry122:
    db 1
    dq idt_handler_122
.entry123:
    db 1
    dq idt_handler_123
.entry124:
    db 1
    dq idt_handler_124
.entry125:
    db 1
    dq idt_handler_125
.entry126:
    db 1
    dq idt_handler_126
.entry127:
    db 1
    dq idt_handler_127
.entry128:
    db 1
    dq idt_handler_128
.entry129:
    db 1
    dq idt_handler_129
.entry130:
    db 1
    dq idt_handler_130
.entry131:
    db 1
    dq idt_handler_131
.entry132:
    db 1
    dq idt_handler_132
.entry133:
    db 1
    dq idt_handler_133
.entry134:
    db 1
    dq idt_handler_134
.entry135:
    db 1
    dq idt_handler_135
.entry136:
    db 1
    dq idt_handler_136
.entry137:
    db 1
    dq idt_handler_137
.entry138:
    db 1
    dq idt_handler_138
.entry139:
    db 1
    dq idt_handler_139
.entry140:
    db 1
    dq idt_handler_140
.entry141:
    db 1
    dq idt_handler_141
.entry142:
    db 1
    dq idt_handler_142
.entry143:
    db 1
    dq idt_handler_143
.entry144:
    db 1
    dq idt_handler_144
.entry145:
    db 1
    dq idt_handler_145
.entry146:
    db 1
    dq idt_handler_146
.entry147:
    db 1
    dq idt_handler_147
.entry148:
    db 1
    dq idt_handler_148
.entry149:
    db 1
    dq idt_handler_149
.entry150:
    db 1
    dq idt_handler_150
.entry151:
    db 1
    dq idt_handler_151
.entry152:
    db 1
    dq idt_handler_152
.entry153:
    db 1
    dq idt_handler_153
.entry154:
    db 1
    dq idt_handler_154
.entry155:
    db 1
    dq idt_handler_155
.entry156:
    db 1
    dq idt_handler_156
.entry157:
    db 1
    dq idt_handler_157
.entry158:
    db 1
    dq idt_handler_158
.entry159:
    db 1
    dq idt_handler_159
.entry160:
    db 1
    dq idt_handler_160
.entry161:
    db 1
    dq idt_handler_161
.entry162:
    db 1
    dq idt_handler_162
.entry163:
    db 1
    dq idt_handler_163
.entry164:
    db 1
    dq idt_handler_164
.entry165:
    db 1
    dq idt_handler_165
.entry166:
    db 1
    dq idt_handler_166
.entry167:
    db 1
    dq idt_handler_167
.entry168:
    db 1
    dq idt_handler_168
.entry169:
    db 1
    dq idt_handler_169
.entry170:
    db 1
    dq idt_handler_170
.entry171:
    db 1
    dq idt_handler_171
.entry172:
    db 1
    dq idt_handler_172
.entry173:
    db 1
    dq idt_handler_173
.entry174:
    db 1
    dq idt_handler_174
.entry175:
    db 1
    dq idt_handler_175
.entry176:
    db 1
    dq idt_handler_176
.entry177:
    db 1
    dq idt_handler_177
.entry178:
    db 1
    dq idt_handler_178
.entry179:
    db 1
    dq idt_handler_179
.entry180:
    db 1
    dq idt_handler_180
.entry181:
    db 1
    dq idt_handler_181
.entry182:
    db 1
    dq idt_handler_182
.entry183:
    db 1
    dq idt_handler_183
.entry184:
    db 1
    dq idt_handler_184
.entry185:
    db 1
    dq idt_handler_185
.entry186:
    db 1
    dq idt_handler_186
.entry187:
    db 1
    dq idt_handler_187
.entry188:
    db 1
    dq idt_handler_188
.entry189:
    db 1
    dq idt_handler_189
.entry190:
    db 1
    dq idt_handler_190
.entry191:
    db 1
    dq idt_handler_191
.entry192:
    db 1
    dq idt_handler_192
.entry193:
    db 1
    dq idt_handler_193
.entry194:
    db 1
    dq idt_handler_194
.entry195:
    db 1
    dq idt_handler_195
.entry196:
    db 1
    dq idt_handler_196
.entry197:
    db 1
    dq idt_handler_197
.entry198:
    db 1
    dq idt_handler_198
.entry199:
    db 1
    dq idt_handler_199
.entry200:
    db 1
    dq idt_handler_200
.entry201:
    db 1
    dq idt_handler_201
.entry202:
    db 1
    dq idt_handler_202
.entry203:
    db 1
    dq idt_handler_203
.entry204:
    db 1
    dq idt_handler_204
.entry205:
    db 1
    dq idt_handler_205
.entry206:
    db 1
    dq idt_handler_206
.entry207:
    db 1
    dq idt_handler_207
.entry208:
    db 1
    dq idt_handler_208
.entry209:
    db 1
    dq idt_handler_209
.entry210:
    db 1
    dq idt_handler_210
.entry211:
    db 1
    dq idt_handler_211
.entry212:
    db 1
    dq idt_handler_212
.entry213:
    db 1
    dq idt_handler_213
.entry214:
    db 1
    dq idt_handler_214
.entry215:
    db 1
    dq idt_handler_215
.entry216:
    db 1
    dq idt_handler_216
.entry217:
    db 1
    dq idt_handler_217
.entry218:
    db 1
    dq idt_handler_218
.entry219:
    db 1
    dq idt_handler_219
.entry220:
    db 1
    dq idt_handler_220
.entry221:
    db 1
    dq idt_handler_221
.entry222:
    db 1
    dq idt_handler_222
.entry223:
    db 1
    dq idt_handler_223
.entry224:
    db 1
    dq idt_handler_224
.entry225:
    db 1
    dq idt_handler_225
.entry226:
    db 1
    dq idt_handler_226
.entry227:
    db 1
    dq idt_handler_227
.entry228:
    db 1
    dq idt_handler_228
.entry229:
    db 1
    dq idt_handler_229
.entry230:
    db 1
    dq idt_handler_230
.entry231:
    db 1
    dq idt_handler_231
.entry232:
    db 1
    dq idt_handler_232
.entry233:
    db 1
    dq idt_handler_233
.entry234:
    db 1
    dq idt_handler_234
.entry235:
    db 1
    dq idt_handler_235
.entry236:
    db 1
    dq idt_handler_236
.entry237:
    db 1
    dq idt_handler_237
.entry238:
    db 1
    dq idt_handler_238
.entry239:
    db 1
    dq idt_handler_239
.entry240:
    db 1
    dq idt_handler_240
.entry241:
    db 1
    dq idt_handler_241
.entry242:
    db 1
    dq idt_handler_242
.entry243:
    db 1
    dq idt_handler_243
.entry244:
    db 1
    dq idt_handler_244
.entry245:
    db 1
    dq idt_handler_245
.entry246:
    db 1
    dq idt_handler_246
.entry247:
    db 1
    dq idt_handler_247
.entry248:
    db 1
    dq idt_handler_248
.entry249:
    db 1
    dq idt_handler_249
.entry250:
    db 1
    dq idt_handler_250
.entry251:
    db 1
    dq idt_handler_251
.entry252:
    db 1
    dq idt_handler_252
.entry253:
    db 1
    dq idt_handler_253
.entry254:
    db 1
    dq idt_handler_254
.entry255:
    db 1
    dq idt_handler_255
